name: cyShop

services:
  cyShopDB:
    image: postgres:17.6
    container_name: cyShopDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cyShopDB-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2
    container_name: redis-basketcache
    ports:
      - "6379:6379"
    volumes:
      - basketcache-data:/data
  
  keycloak-db-init:
    image: postgres:17.6
    container_name: keycloak-db-init
    depends_on:
      cyShopDB:
        condition: service_healthy
    environment:
      PGHOST: cyShopDB
      PGUSER: postgres
      PGPASSWORD: postgres
    entrypoint: >
      bash -c "psql -tc \"SELECT 1 FROM pg_database WHERE datname = 'keycloak'\" | grep -q 1 || psql -c 'CREATE DATABASE keycloak;'"
    restart: "no"

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev
    depends_on:
      keycloak-db-init:
        condition: service_completed_successfully
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: cyShopDB
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
  
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data

  cyShop-opensearch:
    image: opensearchproject/opensearch:2.17.1
    container_name: cyShop-opensearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
    networks:
      - cyshop-network
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ../data/opensearch:/tmp/models
    restart: unless-stopped

  cyShop-opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.17.1
    container_name: cyshop-opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["http://cyShop-opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - cyshop-network
    depends_on:
      - cyShop-opensearch
    restart: unless-stopped

networks:
  cyshop-network:
    driver: bridge

volumes:
  cyShopDB-data:
  basketcache-data:
  keycloak-data:
  rabbitmq-data:
  minio-data:
  opensearch-data:
  redisinsight-data:
